"""Initial migration

Revision ID: 435fc7c22417
Revises: 
Create Date: 2025-09-16 17:17:26.181126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435fc7c22417'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_item_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_item_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_item_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_is_read'), ['is_read'], unique=False)

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletter_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_newsletter_subscribed_at'), ['subscribed_at'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index('idx_order_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_total_amount'), ['total_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_active_featured', ['is_active', 'is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_best_seller'), ['is_best_seller'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_new_arrival'), ['is_new_arrival'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_is_on_sale'), ['is_on_sale'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_stock_quantity'), ['stock_quantity'], unique=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_user_email_active', ['email', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_item_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_item_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_item_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_item_added_at'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_is_active'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index('idx_user_email_active')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_rating'))
        batch_op.drop_index(batch_op.f('ix_review_product_id'))
        batch_op.drop_index(batch_op.f('ix_review_is_approved'))
        batch_op.drop_index(batch_op.f('ix_review_created_at'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_stock_quantity'))
        batch_op.drop_index(batch_op.f('ix_product_sku'))
        batch_op.drop_index(batch_op.f('ix_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_name'))
        batch_op.drop_index(batch_op.f('ix_product_is_on_sale'))
        batch_op.drop_index(batch_op.f('ix_product_is_new_arrival'))
        batch_op.drop_index(batch_op.f('ix_product_is_featured'))
        batch_op.drop_index(batch_op.f('ix_product_is_best_seller'))
        batch_op.drop_index(batch_op.f('ix_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_product_created_at'))
        batch_op.drop_index('idx_product_active_featured')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_total_amount'))
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_payment_status'))
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.drop_index(batch_op.f('ix_order_created_at'))
        batch_op.drop_index('idx_order_user_created')

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscribed_at'))
        batch_op.drop_index(batch_op.f('ix_newsletter_is_active'))
        batch_op.drop_index(batch_op.f('ix_newsletter_email'))

    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_is_read'))
        batch_op.drop_index(batch_op.f('ix_contact_message_email'))
        batch_op.drop_index(batch_op.f('ix_contact_message_created_at'))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index(batch_op.f('ix_category_is_active'))
        batch_op.drop_index(batch_op.f('ix_category_created_at'))

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_cart_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_cart_item_added_at'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
